import React, { useState } from "react";
import Head from "next/head";
import Layout from "../components/layout";
import InvoiceForm from '../components/invoiceForm'
import { IoIosAddCircle } from "react-icons/io";

export default function Home() {
  const [Invoices, setInvoices] = useState([]);
  const [ShowForm, setShowForm] = useState(false)

  const toggleShowForm = () => {
    setShowForm(!ShowForm)
  }
  return (
    <>
      <Head>
        <title>Invoices App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InvoiceForm show={ShowForm} toggleShow={toggleShowForm}/>
      <Layout>
        <div className="w-full flex flex-col items-center px-4 py-8">
          <div className="max-w-5xl w-full flex flex-row justify-between items-center">
            <div className="flex flex-col gap-1">
              <h1 className="font-semibold text-4xl tracking-wide text-black dark:text-white">
                Invoices
              </h1>
              <small className="tracking-wider text-neutral-900 dark:text-neutral-300">
                There are {Invoices.length} total invoices
              </small>
            </div>
            <div className="flex flex-row gap-10">
              <button onClick={toggleShowForm} className="flex flex-row items-center gap-2 bg-[#7C5FF8] rounded-full py-1 px-3 text-white hover:bg-[#6d54dc] transition-colors">
                <IoIosAddCircle size={40} />
                New Invoice
              </button>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
